### ISSUE TITLE
can not open regex text file

### ISSUE THREAD

**Issue by naughtybear** [chrmarti/vscode-regex#13]
When I click 'Test Regex...', I got this promote: 'cannot open file://%5CRegex%20Matches. Detail: Invalid file resource (file://%5Cregex%20matches)'.

For the first several times, it works fine. but now it just can't work. would you help please?
Thanks very much!

**Comment by chrmarti** [comment]
Not sure, maybe there is a file with that name on disk now that wasn't there before? Try deleting that.

Alternatively, you can open a second editor side-by-side yourself, the extension will then use that to match the regex against.

**Comment by naughtybear** [comment]
Hi, there indeed has a file named 'Regex Matches' in d:\ driver.
When delete the file, it works again.

The problem occurred where I save the regex text file. Then close it, and when I try to click 'Test Regex...', the error pops out.

Hopefully, any better solution?

**Comment by chrmarti** [comment]
Thanks, will fix with #11.
