### ISSUE TITLE
Issue opening the matchesFile URI in V0.0.4

### ISSUE THREAD

**Issue by costano** [chrmarti/vscode-regex#2]
by clicking on the "Test Regex..." link within the srcCode in order to test the given Regex i get the error Message: 
cannot open untitled:/Regex%20Matches. Detail: expected URI untitled:/Regex%20Matches BUT GOT untitled:%5CRegex%20Matches

Changing line 13 in ..\.vscode\extensions\chrmarti.regex-0.0.4\out\src\extension.js
from:    var matchesFileUri = vscode.Uri.parse('untitled:/Regex Matches');
to    :    var matchesFileUri = vscode.Uri.parse('untitled:%5CRegex Matches');
...will fix the problem.

**Comment by chrmarti** [comment]
Thanks for catching. Interestingly the suggested fix breaks it on OS X. The original problem only reproduces on Windows.

**Comment by costano** [comment]
You're welcome christof,
yes, also on ubuntu, changing the val of the var will break the extension. 
however, you did a great work with it! :)

**Comment by chrmarti** [comment]
Only later realized your suggestion was to use the platform separator, early Mondays... :)

I've published to fix with v0.0.5.

**Comment by costano** [comment]
sorry it was my fault :), should have mentioned that the bug was just
related on windows plattforms.
anyway, thanks for the fix! keep it up!

**Comment by mredbishop** [comment]
I get cannot open untitled:%5CRegex%20Matches. Detail: file already exists on disk which I think might be  the same or a related issue?
