### ISSUE TITLE
Cannot open untitled:%5CRegex%20Matches

### ISSUE THREAD

**Issue by chrmarti** [chrmarti/vscode-regex#3]
@mredbishop reports in #2: Cannot open untitled:%5CRegex%20Matches. Detail: file already exists on disk

**Comment by chrmarti** [comment]
@mredbishop As a workaround you can use any other document to show the matches in. Just enable the matching by clicking on the 'Test Regex...' link or running the 'Toggle Regex...' command and then any side-by-side editor will show the matches.

**Comment by mredbishop** [comment]
Great thanks :)
