### ISSUE TITLE
Enable for `javascriptreact`, `typescriptreact` languages

### ISSUE THREAD

**Issue by garyking** [chrmarti/vscode-regex#31]
Please enable this great extension for the `javascriptreact` language (and the `typescriptreact` language too). JavaScript regular expressions can obviously be used in React as well, and I default all `.js` files to the `javascriptreact` language in VSC, so it'd be great if this extension would work in that language as well.

Thanks!

**Comment by aztack** [comment]
Thanks for this great extension.
I work daily with *.tsx, *.vue files.
Could you please support those type of files?

**Comment by galangel** [comment]
yes please

**Comment by zardoy** [comment]
This was fixed by https://github.com/chrmarti/vscode-regex/pull/42 btw

**Comment by chrmarti** [comment]
Indeed, thanks for noting and thanks @galangel for the PR.
