### ISSUE TITLE
Breaks on /^$/gmi (Specifically the next time the regex is changed.)

### ISSUE THREAD

**Issue by SMEmp** [chrmarti/vscode-regex#4]
Sought out this extension to get some visual feedback when editing regexes, as I often use them in my day to day work.  However, when starting from the "empty line" regex above (`/^$/gmi`) and extending it, the extension host will terminate.
## Versions:
- Visual Studio Code 1.5.2 
- Ubuntu 16.04
## Reproduction steps:

Two open editor panes.  Left is set to `javascript`, right is set to `plain text`.  Extension is enabled and cursor is in regex body.

`plain text` pane:

```
# Email Test Cases #

Pulled from https://blogs.msdn.microsoft.com/testing123/2009/02/06/email-address-test-cases/

TODO: Remove invalid test cases that should in fact be valid, such as the one assuming TLD validation.


## Valid Email Addresses ##

email@domain.com
firstname.lastname@domain.com
email@subdomain.domain.com
firstname+lastname@domain.com
email@123.123.123.123
email@[123.123.123.123]
"email"@domain.com
1234567890@domain.com
email@domain-one.com
_______@domain.com
email@domain.name
email@domain.co.jp
firstname-lastname@domain.com


## Invalid Email Addresses ##

plainaddress
#@%^%#$@#$@#.com
@domain.com
Joe Smith <email@domain.com>
email.domain.com
email@domain@domain.com
.email@domain.com
email.@domain.com
email..email@domain.com
あいうえお@domain.com
email@domain.com (Joe Smith)
email@domain
email@-domain.com
email@domain.web
email@111.222.333.44444
email@domain..com
```

`javascript` pane:

```
var emailPattern = /^$/gmi;
```

To trigger an extension failure, place the cursor between `^` and `$` in the `javascript` pane and enter a character such as `e`.
### Expected result:

Right pane has 0 entries highlighted until finished changing `/^$/gmi` to something like `/^email.*$/gmi`, at which point entries matching that regex should become highlighted.
### Actual result:

`[Error] Extension host terminated unexpectedly.  Please reload the window to recover. [Reload Window]`
`[Error] Error from the extension host: channel closed [Close]`

**Comment by chrmarti** [comment]
@SMEmp Thanks for the detailed steps to reproduce!
