### ISSUE TITLE
Please add an option to automatically support gm expression flags

### ISSUE THREAD

**Issue by TheNightbear** [chrmarti/vscode-regex#5]
I don't want to add "/gm" expression flags to my regular expressions, because of a requirement of my IDE or in this case an extension I want to use . 

But unfortunately Regex Previewer force me to this if I want to check my regex against multiple values.

It would be better to have an option available where I can decide case by case. E.g. the clickable "Test regex..." could offer an "globally multiline" option.

**Comment by SMEmp** [comment]
There are many times I want to have a regex test one specific value (first pass of input validation comes to mind) but test the regex itself while writing it against a test suite of valid and invalid values.  Regex Previewer allows a live environment for testing, but the requirement to change my code to accommodate it is worrying at best.
