### ISSUE TITLE
Short cut, all though correctly assigned fails to present any window; there's also no command palette option to toggle this window.

### ISSUE THREAD

**Issue by atengberg** [chrmarti/vscode-regex#68]
In Ubuntu 20.04 TLS using VSCode version 1.94.2  after downloading the extension version 0.5.0, the `crtl + alt + m` shortcut fails to materialize any side by side window. Confirmed the extension is installed, the short cut key is registered as expected. If related, there's no option from the autocomplete suggestions when using the command palette to manually open the window. 

Maybe I am missing something incredibly obvious? 

I can provide more details just let me know what's relevant to share.

**Comment by chrmarti** [comment]
Did the extension activate? (`F1` > `Developer: Show Running Extensions`)

**Comment by atengberg** [comment]
Yes.
