### ISSUE TITLE
Can this work on ubuntu?

### ISSUE THREAD

**Issue by Steven-AA** [chrmarti/vscode-regex#9]
VS Code 1.9.1
ubuntu 14.04

When I turn it on, the 'Regex Matches' will be open, but nothing is matched and 'Test Regex...' cannot be seen in the code.

**Comment by chrmarti** [comment]
Which language are you using?

**Comment by Steven-AA** [comment]
@chrmarti js

**Comment by chrmarti** [comment]
@Steven-AA What's your regex and what text are you matching it against?

**Comment by Steven-AA** [comment]
Sorry to bother， I am learning js and I used wrong regex.
